// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJ-oGFdPuXYfZt7PW52qZ23BlgjBNaXE',
    appId: '1:69948732099:web:7a8766fd36cd71555a2876',
    messagingSenderId: '69948732099',
    projectId: 'relacional-7f17d',
    authDomain: 'relacional-7f17d.firebaseapp.com',
    databaseURL: 'https://relacional-7f17d.firebaseio.com',
    storageBucket: 'relacional-7f17d.firebasestorage.app',
    measurementId: 'G-9HT7PERS70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXkjvdUMZWKB4fYuNctAJxd7iJuG3lPRg',
    appId: '1:69948732099:android:493f26a84c6913bf5a2876',
    messagingSenderId: '69948732099',
    projectId: 'relacional-7f17d',
    databaseURL: 'https://relacional-7f17d.firebaseio.com',
    storageBucket: 'relacional-7f17d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj5-_D-Q-JRyI3jKl1bzkfvrJ1co-ikTY',
    appId: '1:69948732099:ios:6e6422a2ff7c29c25a2876',
    messagingSenderId: '69948732099',
    projectId: 'relacional-7f17d',
    databaseURL: 'https://relacional-7f17d.firebaseio.com',
    storageBucket: 'relacional-7f17d.firebasestorage.app',
    androidClientId: '69948732099-rvb8getbluejljht62qa3ov2dv8l0ued.apps.googleusercontent.com',
    iosClientId: '69948732099-gp315iagcqadra9gldg2nl6li7oj1fj9.apps.googleusercontent.com',
    iosBundleId: 'com.smartodds.smartOdds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj5-_D-Q-JRyI3jKl1bzkfvrJ1co-ikTY',
    appId: '1:69948732099:ios:6e6422a2ff7c29c25a2876',
    messagingSenderId: '69948732099',
    projectId: 'relacional-7f17d',
    databaseURL: 'https://relacional-7f17d.firebaseio.com',
    storageBucket: 'relacional-7f17d.firebasestorage.app',
    androidClientId: '69948732099-rvb8getbluejljht62qa3ov2dv8l0ued.apps.googleusercontent.com',
    iosClientId: '69948732099-gp315iagcqadra9gldg2nl6li7oj1fj9.apps.googleusercontent.com',
    iosBundleId: 'com.smartodds.smartOdds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtJ-oGFdPuXYfZt7PW52qZ23BlgjBNaXE',
    appId: '1:69948732099:web:7377b8b82c43bd275a2876',
    messagingSenderId: '69948732099',
    projectId: 'relacional-7f17d',
    authDomain: 'relacional-7f17d.firebaseapp.com',
    databaseURL: 'https://relacional-7f17d.firebaseio.com',
    storageBucket: 'relacional-7f17d.firebasestorage.app',
    measurementId: 'G-G3LZ9SQZMB',
  );
}
